// Inspired from:

/////////////////////////////////////////////////////////////////
// Batch Export Unlocked Layers v2 -- CS5
//>=--------------------------------------
//	This script will generate a separate raster image for every UNLOCKED layer in your .ai file.  
// 
//	Locked images will be left as is.
//	To <b>hide</b> any layer; 
//	Lock it, and hide it on the Layers palate before running this script.
//	
//	To <b>include</b> a layer in every image:
//	Lock it, and make sure it's visible before running this script.
//
//	This script auto-generates a production script into the image export directory,
//	so if you ever need to re-run the script, just re-open all the same source files, 
//	double click the .jsx file in your image export directory, and it will re-export
//  all the images with the same settings.
//  MUCH thanks to Chris Gebab for help brainstorming
//  a hack to get this working as a palette in illustrator.
//  For more info, see my <a href="http://js4ai.blogspot.com/2010/06/export-layers-as-images.html">blog</a>
// update: v2 adds ability to scale the exported images.
//>=--------------------------------------
// JS code (c) copyright: John Wundes ( john@wundes.com ) www.wundes.com
//copyright full text here:  http://www.wundes.com/js4ai/copyright.txt
////////////////////////////////////////////////////////////////// 


// Usage, create a file with following content:
//
//
// #include "path/to/dotfiles/scripts/illustrator.jsx"
//
// exportLayers({
//      exportFileType: 'PNG',
//      baseFilename: 'filename',
//      save_location: '/path/to/destination',
//      img_scale: 40
//  })

var fname = app.activeDocument.name;
fname = fname.substr(0,fname.lastIndexOf("."));

var fileNameConst = fname;
var filename = fileNameConst;


function exportLayers(conf) {
    var c = {
        filesBool: false,
        baseFilename: '',
        separator: '_',
        layerNameBool: true,
        exportFileType: 'JPG',
        img_aa: true,
        img_clip: true,
        jpg_quality: 85,
        img_trans: true,
        img_scale: 100,
        save_location: '~'
    }

    for (var key in c) {
        if (conf[key]) c[key] = conf[key]
    }

    conf = c
    conf.tmp_script = conf.save_location+"/Export"+conf.exportFileType+".jsx"

    var myFile = new File(conf.tmp_script);
    var content= renderExportScript(conf);
    myFile.open("w"); // 'w' overwrites whatever is there.
    myFile.write(content);
    myFile.close();          
    myFile.execute();
}


function  exportValues(conf){

}

// NON-UI FUNCTION BELOW:
function renderExportScript(c){
    var newFileBody = " #target illustrator\
\
//This file was autogenerated by BatchExportUI.jsx from wundes.com\
// it is safe to erase, as it will be recreated the next time exportLayers.jsx is run.\
var fileName = '';\
doIt();\
function doIt(){    \
    // for each layer\
    if("+c.filesBool+"){\
        var allDocsLen = app.documents.length;\
        while (allDocsLen--){\
            app.documents[app.documents.length-1].activate();\
            redraw();\
            processDocument(app.documents[0]);\
        }\
    }else{\
           processDocument(app.activeDocument);\
    }\
}\
\
function processDocument(currDoc){\
\
    doc = currDoc;\
    var len = doc.layers.length;\
    var fname = doc.name;\
    fname = fname.substr(0,fname.lastIndexOf(\".\"));\
    fileName = \""+c.baseFilename+"\" == \""+fileNameConst+"\" ? fname : \""+c.baseFilename+"\";\
    while (len--){\
        //if layer isn't locked\
        var thisLayer = doc.layers[len];\
        if(thisLayer.locked == false){\
            hideAllUnlocked();\
            thisLayer.visible=true;\
            app.redraw();\
\
\
            var suffix =  "+c.layerNameBool+" ? thisLayer.name:len;\
            switch(\""+c.exportFileType+"\") {\
                case \"JPG\":\
                    exportJPG(suffix);\
                    break;\
                case \"GIF\":\
                    exportGIF(suffix);\
                    break;\
                case\"PNG\":\
                    exportPNG(suffix);\
                    break;\
                default:\
                    break;\
            }\
        }\
    }\
\
    // finally show all layers\
    for (var i = 0; i < doc.layers.length; i++) {\
        doc.layers[i].visible = true\
    }\
\
    var f = new File('"+c.tmp_script+"');\
    f.remove();\
}\
\
function hideAllUnlocked(){\
    var all = doc.layers.length;\
    while(all--){\
        if( doc.layers[all].locked==false){\
            doc.layers[all].visible=false;\
        }\
    }\
}\
\
function exportJPG(num){\
     var exportOptions = new ExportOptionsJPEG();   \
    var exportName = (\""+c.save_location+"\"+\"/\"+ fileName+\""+c.separator+"\"+num);\
    var dest = new File(exportName);\
    var type = ExportType.JPEG;\
    exportOptions.antiAliasing = "+c.img_aa+";\
    exportOptions.qualitySetting = "+c.jpg_quality+";\
    exportOptions.horizontalScale = "+c.img_scale+";\
    exportOptions.verticalScale = "+c.img_scale+";\
    exportOptions.optimization=true;\
    exportOptions.artBoardClipping="+c.img_clip+";\
\
    doc.exportFile(dest,type,exportOptions);\
}\
function exportGIF(num){\
     var exportOptions = new ExportOptionsGIF(); \
    var exportName = (\""+c.save_location+"\"+\"/\"+ fileName+\""+c.separator+"\"+num);\
    var dest = new File(exportName);\
    var type = ExportType.GIF;\
     exportOptions.antiAliasing = "+c.img_aa+";\
     exportOptions.artBoardClipping="+c.img_clip+";\
     exportOptions.transparency="+c.img_trans+" ;\
     exportOptions.horizontalScale = "+c.img_scale+";\
     exportOptions.verticalScale = "+c.img_scale+";\
    doc.exportFile(dest,type,exportOptions);\
}\
function exportPNG(num){\
     var exportOptions = new ExportOptionsPNG24();  \
    var exportName = (\""+c.save_location+"\"+\"/\"+ fileName+\""+c.separator+"\"+num);\
    var dest = new File(exportName);\
    var type = ExportType.PNG24;\
     exportOptions.antiAliasing = "+c.img_aa+";\
     exportOptions.artBoardClipping="+c.img_clip+";\
     exportOptions.transparency="+c.img_trans+" ;\
     exportOptions.horizontalScale = "+c.img_scale+";\
     exportOptions.verticalScale = "+c.img_scale+";\
    doc.exportFile(dest,type,exportOptions); \
}";

    return newFileBody;
}
